package s_gestrion_notificaciones.sop_corba;


/**
* s_gestrion_notificaciones/sop_corba/AlertaDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificacion.idl
* martes 15 de marzo de 2022 09H14' COT
*/

public final class AlertaDTO implements org.omg.CORBA.portable.IDLEntity
{
  public s_gestrion_notificaciones.sop_corba.LecturaDTO listaLecturas[] = null;

  public AlertaDTO ()
  {
  } // ctor

  public AlertaDTO (s_gestrion_notificaciones.sop_corba.LecturaDTO[] _listaLecturas)
  {
    listaLecturas = _listaLecturas;
  } // ctor

} // class AlertaDTO
