package s_gestrion_notificaciones.sop_corba;


/**
* s_gestrion_notificaciones/sop_corba/AlertaDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificacion.idl
* martes 15 de marzo de 2022 09H14' COT
*/

abstract public class AlertaDTOHelper
{
  private static String  _id = "IDL:sop_corba/AlertaDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, s_gestrion_notificaciones.sop_corba.AlertaDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static s_gestrion_notificaciones.sop_corba.AlertaDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = s_gestrion_notificaciones.sop_corba.LecturaDTOHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (s_gestrion_notificaciones.sop_corba.ArrayLecturasHelper.id (), "ArrayLecturas", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "listaLecturas",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (s_gestrion_notificaciones.sop_corba.AlertaDTOHelper.id (), "AlertaDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static s_gestrion_notificaciones.sop_corba.AlertaDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    s_gestrion_notificaciones.sop_corba.AlertaDTO value = new s_gestrion_notificaciones.sop_corba.AlertaDTO ();
    value.listaLecturas = s_gestrion_notificaciones.sop_corba.ArrayLecturasHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, s_gestrion_notificaciones.sop_corba.AlertaDTO value)
  {
    s_gestrion_notificaciones.sop_corba.ArrayLecturasHelper.write (ostream, value.listaLecturas);
  }

}
