package s_gestrion_notificaciones.sop_corba;


/**
* s_gestrion_notificaciones/sop_corba/GestionNotificacionesIntHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificacion.idl
* martes 15 de marzo de 2022 09H14' COT
*/

abstract public class GestionNotificacionesIntHelper
{
  private static String  _id = "IDL:sop_corba/GestionNotificacionesInt:1.0";

  public static void insert (org.omg.CORBA.Any a, s_gestrion_notificaciones.sop_corba.GestionNotificacionesInt that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static s_gestrion_notificaciones.sop_corba.GestionNotificacionesInt extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (s_gestrion_notificaciones.sop_corba.GestionNotificacionesIntHelper.id (), "GestionNotificacionesInt");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static s_gestrion_notificaciones.sop_corba.GestionNotificacionesInt read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GestionNotificacionesIntStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, s_gestrion_notificaciones.sop_corba.GestionNotificacionesInt value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static s_gestrion_notificaciones.sop_corba.GestionNotificacionesInt narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof s_gestrion_notificaciones.sop_corba.GestionNotificacionesInt)
      return (s_gestrion_notificaciones.sop_corba.GestionNotificacionesInt)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      s_gestrion_notificaciones.sop_corba._GestionNotificacionesIntStub stub = new s_gestrion_notificaciones.sop_corba._GestionNotificacionesIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static s_gestrion_notificaciones.sop_corba.GestionNotificacionesInt unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof s_gestrion_notificaciones.sop_corba.GestionNotificacionesInt)
      return (s_gestrion_notificaciones.sop_corba.GestionNotificacionesInt)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      s_gestrion_notificaciones.sop_corba._GestionNotificacionesIntStub stub = new s_gestrion_notificaciones.sop_corba._GestionNotificacionesIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
