package s_gestrion_notificaciones.sop_corba;


/**
* s_gestrion_notificaciones/sop_corba/LecturaDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificacion.idl
* martes 15 de marzo de 2022 09H14' COT
*/

abstract public class LecturaDTOHelper
{
  private static String  _id = "IDL:sop_corba/LecturaDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, s_gestrion_notificaciones.sop_corba.LecturaDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static s_gestrion_notificaciones.sop_corba.LecturaDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "nombreZona",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "tiempoCaptura",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "temperatura",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[3] = new org.omg.CORBA.StructMember (
            "humedad",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "precipitacion",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (s_gestrion_notificaciones.sop_corba.LecturaDTOHelper.id (), "LecturaDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static s_gestrion_notificaciones.sop_corba.LecturaDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    s_gestrion_notificaciones.sop_corba.LecturaDTO value = new s_gestrion_notificaciones.sop_corba.LecturaDTO ();
    value.nombreZona = istream.read_string ();
    value.tiempoCaptura = istream.read_string ();
    value.temperatura = istream.read_long ();
    value.humedad = istream.read_long ();
    value.precipitacion = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, s_gestrion_notificaciones.sop_corba.LecturaDTO value)
  {
    ostream.write_string (value.nombreZona);
    ostream.write_string (value.tiempoCaptura);
    ostream.write_long (value.temperatura);
    ostream.write_long (value.humedad);
    ostream.write_long (value.precipitacion);
  }

}
