package s_gestrion_notificaciones.sop_corba;


/**
* s_gestrion_notificaciones/sop_corba/LecturaDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificacion.idl
* martes 15 de marzo de 2022 09H14' COT
*/

public final class LecturaDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String nombreZona = null;
  public String tiempoCaptura = null;
  public int temperatura = (int)0;
  public int humedad = (int)0;
  public int precipitacion = (int)0;

  public LecturaDTO ()
  {
  } // ctor

  public LecturaDTO (String _nombreZona, String _tiempoCaptura, int _temperatura, int _humedad, int _precipitacion)
  {
    nombreZona = _nombreZona;
    tiempoCaptura = _tiempoCaptura;
    temperatura = _temperatura;
    humedad = _humedad;
    precipitacion = _precipitacion;
  } // ctor

} // class LecturaDTO
