package s_gestion_alarmas.sop_corba;

/**
* s_gestion_alarmas/sop_corba/AlertaDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificacion.idl
* martes 15 de marzo de 2022 09H40' COT
*/

public final class AlertaDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public s_gestion_alarmas.sop_corba.AlertaDTO value = null;

  public AlertaDTOHolder ()
  {
  }

  public AlertaDTOHolder (s_gestion_alarmas.sop_corba.AlertaDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = s_gestion_alarmas.sop_corba.AlertaDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    s_gestion_alarmas.sop_corba.AlertaDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return s_gestion_alarmas.sop_corba.AlertaDTOHelper.type ();
  }

}
