package s_gestion_alarmas.sop_corba;


/**
* s_gestion_alarmas/sop_corba/GestionNotificacionesIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificacion.idl
* martes 15 de marzo de 2022 09H40' COT
*/

public interface GestionNotificacionesIntOperations 
{
  void enviarNorificacion (s_gestion_alarmas.sop_corba.AlertaDTO objAlerta);
} // interface GestionNotificacionesIntOperations
