package s_gestion_alarmas.sop_corba;


/**
* s_gestion_alarmas/sop_corba/GestionNotificacionesInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificacion.idl
* martes 15 de marzo de 2022 09H40' COT
*/

public interface GestionNotificacionesInt extends GestionNotificacionesIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionNotificacionesInt
