package s_gestion_alarmas.sop_corba;


/**
* s_gestion_alarmas/sop_corba/GestionNotificacionesIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificacion.idl
* martes 15 de marzo de 2022 09H40' COT
*/

public abstract class GestionNotificacionesIntPOA extends org.omg.PortableServer.Servant
 implements s_gestion_alarmas.sop_corba.GestionNotificacionesIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("enviarNorificacion", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/GestionNotificacionesInt/enviarNorificacion
       {
         s_gestion_alarmas.sop_corba.AlertaDTO objAlerta = s_gestion_alarmas.sop_corba.AlertaDTOHelper.read (in);
         this.enviarNorificacion (objAlerta);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionNotificacionesInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionNotificacionesInt _this() 
  {
    return GestionNotificacionesIntHelper.narrow(
    super._this_object());
  }

  public GestionNotificacionesInt _this(org.omg.CORBA.ORB orb) 
  {
    return GestionNotificacionesIntHelper.narrow(
    super._this_object(orb));
  }


} // class GestionNotificacionesIntPOA
