package s_gestion_alarmas.sop_corba;

/**
* s_gestion_alarmas/sop_corba/LecturaDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificacion.idl
* martes 15 de marzo de 2022 09H40' COT
*/

public final class LecturaDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public s_gestion_alarmas.sop_corba.LecturaDTO value = null;

  public LecturaDTOHolder ()
  {
  }

  public LecturaDTOHolder (s_gestion_alarmas.sop_corba.LecturaDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = s_gestion_alarmas.sop_corba.LecturaDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    s_gestion_alarmas.sop_corba.LecturaDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return s_gestion_alarmas.sop_corba.LecturaDTOHelper.type ();
  }

}
